kind: Deployment
apiVersion: apps/v1
metadata:
  name: quote-svc
  labels:
    app: quote-svc
    workshop: workshop
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: quote-svc
  template:
    metadata:
      labels:
        app: quote-svc
        workshop: workshop
    spec:
      containers:
        - name: quote-svc
          image: bashofmann/k8s-workshop-quote-svc:8.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 1
