kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "web-application.fullname" . }}-config
  labels:
    helm.sh/chart: {{ include "web-application.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    workshop: workshop
data:
  COMPANY_NAME: "{{ .Values.company }}"
  DB_HOST: mysql-cluster-mysql-master
  DB_USER: root
